### ISSUE TITLE
[bug] Windows client  start url  error

### ISSUE THREAD

**Issue by yann-y** [Titannet-dao/titan-node#19]
![image](https://github.com/Titannet-dao/titan-node/assets/42291730/c35b1da7-8d95-41ad-b353-744a0fcd6a6f)

**Comment by TitanNet** [comment]
Hi @yann-y 
You can "pause" and then exit the program.
Then download the latest installer, replace it, and run it with the latest program. That should solve the problem.

If it doesn't work, please contact us at TG and we will be happy to help you.
