### ISSUE TITLE
Titan doesn't seem to work on Centos

### ISSUE THREAD

**Issue by huangsiyuan924** [Titannet-dao/titan-node#21]
When I install Titan and try to start it: `titan-edge daemon start --init --url https://test-locator.titannet.io:5000/rpc/v0`

output：
```
2024-03-14T20:12:37.876+0800	INFO	main	titan-edge/main.go:156	Starting titan edge node
2024-03-14T20:12:42.967+0800	ERROR	main	titan-edge/main.go:106	RPC client error: sendRequest failed: Post "https://test-locator.titannet.io:5000/rpc/v0": INTERNAL_ERROR (local): write udp [::]:38048->47.242.3.255:5000: sendmsg: invalid argument
```

I tested that this phenomenon does not appear on Ubuntu, but only on Centos (mine is 7.9).

**Comment by TitanNet** [comment]
50% of the time it's a network issue.

50% chance it is a bug in the code, we will try to fix it in the next update.

**Comment by zscboy** [comment]
export QUIC_GO_DISABLE_ECN=true

**Comment by zscboy** [comment]
Setting the environment variable QUIC_GO_DISABLE_ECN=true will solve this problem on linux:
export QUIC_GO_DISABLE_ECN=true

**Comment by zscboy** [comment]
Setting the environment variable QUIC_GO_DISABLE_ECN=true will solve this problem.
on linux:
export QUIC_GO_DISABLE_ECN=true

**Comment by huangsiyuan924** [comment]
> Setting the environment variable QUIC_GO_DISABLE_ECN=true will solve this problem. on linux: export QUIC_GO_DISABLE_ECN=true

Thanks sir, it solved my problem!

**Comment by Zhucan123** [comment]
have you fix this bug now? it also appear at my machine.

**Comment by huangsiyuan924** [comment]
> have you fix this bug now? it also appear at my machine.

You can follow this: [](https://github.com/Titannet-dao/titan-node/issues/21#issuecomment-2003281047)

**Comment by huangsiyuan924** [comment]
> have you fix this bug now? it also appear at my machine.

https://github.com/Titannet-dao/titan-node/issues/21#issuecomment-2003281047
