### ISSUE TITLE
docker运行失败

### ISSUE THREAD

**Issue by yujianhui1993** [Titannet-dao/titan-node#25]
提示错误
ERROR main titan-edge/main.go:106 RPC client error: sendRequest failed: Post "https://test-locator.titannet.io:5000/rpc/v0": INTERNAL_ERROR (local): write udp [::]:43451->47.76.71.193:5000: sendmsg: invalid argument

**Comment by TitanNet** [comment]
You can get help through our TG community!
https://t.me/titannet_dao

**Comment by MaryTitan** [comment]
Setting the environment variable QUIC_GO_DISABLE_ECN=true will solve this problem.
on linux:
export QUIC_GO_DISABLE_ECN=true

**Comment by ITLiuQing** [comment]
我也遇到这个问题了，怎么解决？

**Comment by ITLiuQing** [comment]
![image](https://github.com/Titannet-dao/titan-node/assets/18901245/977ae4ed-8450-405c-a866-f14e03327b1a)
我设置了，还是不行

**Comment by ysyabc** [comment]
同样的问题，有没有办法解决？

**Comment by MaryTitan** [comment]
> 同样的问题，有没有办法解决？

Please offer your system and version info. Thank you.

**Comment by ZackJiang21** [comment]
> > 同样的问题，有没有办法解决？
> 
> Please offer your system and version info. Thank you.

I am running on CentOS 7.6
