### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by daizheng-code** [Titannet-dao/titan-node#27]
ERROR	main	titan-edge/main.go:106	RPC client error: sendRequest failed: Post "https://test-locator.titannet.io:5000/rpc/v0": INTERNAL_ERROR (local): write udp [::]:45287->47.76.71.193:5000: sendmsg: invalid argument

**Comment by MaryTitan** [comment]
Setting the environment variable QUIC_GO_DISABLE_ECN=true will solve this problem.
on linux:
export QUIC_GO_DISABLE_ECN=true
