### ISSUE TITLE
registering edge failed

### ISSUE THREAD

**Issue by lyx2008** [Titannet-dao/titan-node#34]
INFO    main    titan-edge/main.go:156  Starting titan edge node
INFO    main    titan-edge/main.go:270  Remote version 0.1.16+0403_2+api1.0.0
INFO    builder node/builder_edge.go:46 start to config edge
INFO    main    titan-edge/main.go:370  Edge listen on tcp/udp 0.0.0.0:1234
INFO    main    titan-edge/main.go:403  Making sure no local tasks are running
ERROR   main    titan-edge/main.go:412  Registering edge failed: The node e_72e2daee-4c14-4529-8a41-fe369d0d377c has been deactivate and cannot be logged in
WARN    main    titan-edge/main.go:351  Shutting down...
WARN    main    titan-edge/main.go:617  http3 server closing
ERROR   main    titan-edge/main.go:106  http: Server closed

**Comment by MaryTitan** [comment]
You have exceeded the limit of max 5 nodes under one IP, so the over-limit nodes were deactivated.
