### ISSUE TITLE
creating node

### ISSUE THREAD

**Issue by yan253319066** [Titannet-dao/titan-node#35]
`creating node:
    main.glob..func3
        /root/titan_v0.1.16/cmd/titan-edge/main.go:332
  - starting node:
    github.com/Filecoin-Titan/titan/node.New
        /root/titan_v0.1.16/node/builder.go:139
  - soft file descriptor limit (ulimit -n) too low, want 10000, current 4096:
    github.com/Filecoin-Titan/titan/node/modules.CheckFdLimit
        /root/titan_v0.1.16/node/modules/common.go:126`

What's the problem, please?  System centos7.6

**Comment by zscboy** [comment]
ulimit -n 10000

**Comment by zscboy** [comment]
soft file descriptor small then 10000

**Comment by nezha90** [comment]
The file descriptor limit is the maximum number of files that Linux can open,Here you need to set it larger. search for "centos ulimit" there will be more information
