### ISSUE TITLE
heartbeat: keepalive failed

### ISSUE THREAD

**Issue by mengxuanliang** [Titannet-dao/titan-node#36]
titan-edge/main.go:429  heartbeat: keepalive failed: RPC client error: sendRequest failed: Post "https://test15-scheduler.titannet.io:3456/rpc/v0": timeout: no recent network activity

always,how to fix?

**Comment by srankXY** [comment]
are you ok? bro, i have this err too

**Comment by mengxuanliang** [comment]
still not work,the time wasted in reconnect!!

**Comment by MaryTitan** [comment]
Please try to switch your url with any of these: https://hk-locator.titannet.io:5000/rpc/v0; https://sg-locator.titannet.io:5000/rpc/v0; https://us-locator.titannet.io:5000/rpc/v0
