### ISSUE TITLE
心跳检测异常

### ISSUE THREAD

**Issue by srankXY** [Titannet-dao/titan-node#37]
titan-edge/main.go:429  heartbeat: keepalive failed: RPC client error: sendRequest failed: Post "https://test13-scheduler.titannet.io:3456/rpc/v0": timeout: no recent network activity
![1712624034542](https://github.com/Titannet-dao/titan-node/assets/107738188/79c4368b-3c32-4e27-af05-a0d667dcf45f)

**Comment by MaryTitan** [comment]
https://hk-locator.titannet.io:5000/rpc/v0
