### ISSUE TITLE
Registrations exceeded the number

### ISSUE THREAD

**Issue by DSPerson** [Titannet-dao/titan-node#39]

**Comment by DSPerson** [comment]
version: 1.4

**Comment by beck-8** [comment]
?

**Comment by beck-8** [comment]
你的问题是什么？

**Comment by DSPerson** [comment]
我在docker中使用的时候 Error: Registrations exceeded the number
就是这个

**Comment by beck-8** [comment]
写的很清楚，超过限制

**Comment by DSPerson** [comment]
我就开了一个啊
<img width="1118" alt="image" src="https://github.com/Titannet-dao/titan-node/assets/17868782/26f29452-f9ea-48d6-9fda-bb832b6786d5">

**Comment by DSPerson** [comment]
<img width="1119" alt="image" src="https://github.com/Titannet-dao/titan-node/assets/17868782/9ce2fa53-ef1e-4428-8ed8-4fa97b957a62">

**Comment by MaryTitan** [comment]
Your registrations (not the node numbers) are over the limit. Probably because you deleted old containers and generated new ones, which all were counted as registrations.
