### ISSUE TITLE
Seeing 'Invaild para' when binding code using Windows visual client

### ISSUE THREAD

**Issue by iridium-soda** [Titannet-dao/titan-node#40]
![image](https://github.com/Titannet-dao/titan-node/assets/32727642/3b0f3493-3d9d-4406-bd14-35ddb842d326)
I am sure I typed the correct identity code cause I used copy and paste directly from my dashboard. How can I fix it and bind to my account?
![image](https://github.com/Titannet-dao/titan-node/assets/32727642/610ccba0-8862-4b81-ae2e-50770dfcebaa)

- Windows 11
- The latest GUI release

**Comment by MaryTitan** [comment]
Restart your node, run it for a while til there are earnings. Then try to bind your identity code again. Please remember to enter the last digit of the code manually.

**Comment by iridium-soda** [comment]
It seems it goes well after a while, maybe a temp network failed. Could you mark it as solved?
