### ISSUE TITLE
RPC client error: sendRequest failed: Post "https://test10-scheduler.titannet.io:3456/rpc/v0": timeout: no recent network activity

### ISSUE THREAD

**Issue by vinatechpro** [Titannet-dao/titan-node#45]
![Screenshot 2024-04-19 172505](https://github.com/Titannet-dao/titan-node/assets/149946061/9c8ff073-cf90-4297-9736-79d1d83bafde)

Please update new RPC.

**Comment by MaryTitan** [comment]
For those who report ‘no access point’, or ‘no recent network activity’, please change the url into one of these:
https://hk-locator.titannet.io:5000/rpc/v0
https://sg-locator.titannet.io:5000/rpc/v0
https://us-locator.titannet.io:5000/rpc/v0

**Comment by KafCoppelia** [comment]
I tried all urls but all failed

**Comment by MaryTitan** [comment]
> I tried all urls but all failed

Can I see your error logs?

**Comment by baijuexzz** [comment]
> > I tried all urls but all failed我试了所有的网址，但都失败了
> 
> Can I see your error logs?
> 
> 我能看看你的错误日志吗？
![image](https://github.com/Titannet-dao/titan-node/assets/48422218/0c71e91e-d9e3-4ed1-b926-3928fa28fce6)



> > I tried all urls but all failed
> 
> Can I see your error logs?

![Uploading image.png…]()
What am I supposed to do?

**Comment by KafCoppelia** [comment]
> > I tried all urls but all failed
> 
> Can I see your error logs?

I used titan node in docker.

```bash
2024-05-07T01:13:05.231Z        ERROR   main    titan-edge/main.go:108  RPC client error: sendRequest failed: Post "https://hk-locator.titannet.io:5000/rpc/v0": timeout: no recent network activity
2024-05-07T01:13:06.459Z        INFO    main    titan-edge/main.go:455  Starting titan edge node
2024/05/07 01:13:06 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2024-05-07T01:13:54.184Z        ERROR   main    titan-edge/main.go:108  RPC client error: sendRequest failed: Post "https://hk-locator.titannet.io:5000/rpc/v0": timeout: no recent network activity
2024-05-07T01:13:55.260Z        INFO    main    titan-edge/main.go:455  Starting titan edge node
2024/05/07 01:13:55 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2024-05-07T01:14:41.441Z        ERROR   main    titan-edge/main.go:108  RPC client error: sendRequest failed: Post "https://hk-locator.titannet.io:5000/rpc/v0": timeout: no recent network activity
```

**Comment by MaryTitan** [comment]
> > > I tried all urls but all failed
> > 
> > 
> > Can I see your error logs?
> 
> I used titan node in docker.
> 
> ```shell
> 2024-05-07T01:13:05.231Z        ERROR   main    titan-edge/main.go:108  RPC client error: sendRequest failed: Post "https://hk-locator.titannet.io:5000/rpc/v0": timeout: no recent network activity
> 2024-05-07T01:13:06.459Z        INFO    main    titan-edge/main.go:455  Starting titan edge node
> 2024/05/07 01:13:06 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
> 2024-05-07T01:13:54.184Z        ERROR   main    titan-edge/main.go:108  RPC client error: sendRequest failed: Post "https://hk-locator.titannet.io:5000/rpc/v0": timeout: no recent network activity
> 2024-05-07T01:13:55.260Z        INFO    main    titan-edge/main.go:455  Starting titan edge node
> 2024/05/07 01:13:55 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
> 2024-05-07T01:14:41.441Z        ERROR   main    titan-edge/main.go:108  RPC client error: sendRequest failed: Post "https://hk-locator.titannet.io:5000/rpc/v0": timeout: no recent network activity
> ```

I am afraid this is due to your poor network. You may try to switch to a different network if possible.

**Comment by KafCoppelia** [comment]
> > > > I tried all urls but all failed
> > > 
> > > 
> > > Can I see your error logs?
> > 
> > 
> > I used titan node in docker.
> > ```shell
> > 2024-05-07T01:13:05.231Z        ERROR   main    titan-edge/main.go:108  RPC client error: sendRequest failed: Post "https://hk-locator.titannet.io:5000/rpc/v0": timeout: no recent network activity
> > 2024-05-07T01:13:06.459Z        INFO    main    titan-edge/main.go:455  Starting titan edge node
> > 2024/05/07 01:13:06 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
> > 2024-05-07T01:13:54.184Z        ERROR   main    titan-edge/main.go:108  RPC client error: sendRequest failed: Post "https://hk-locator.titannet.io:5000/rpc/v0": timeout: no recent network activity
> > 2024-05-07T01:13:55.260Z        INFO    main    titan-edge/main.go:455  Starting titan edge node
> > 2024/05/07 01:13:55 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
> > 2024-05-07T01:14:41.441Z        ERROR   main    titan-edge/main.go:108  RPC client error: sendRequest failed: Post "https://hk-locator.titannet.io:5000/rpc/v0": timeout: no recent network activity
> > ```
> 
> I am afraid this is due to your poor network. You may try to switch to a different network if possible.

Thanks
