### ISSUE TITLE
提案：进行POA验证测速时，应当由多个验证节点依次发起验证

### ISSUE THREAD

**Issue by GoudanWoo** [Titannet-dao/titan-node#47]
当前每次POA只会给一个验证节点指派测试任务，但是由于地域/运营商/验证节点负载情况等原因，单次验证并不能很好地反映边缘节点的真实带宽情况。

应当在新建POA任务时，将任务依次/同时下发给3-5个验证节点以进行测速（依次下发可避免同时发起造成带宽挤占，同时下发可更好反应边缘节点性能情况）并剔除失败的测速任务，最终取均值/求和（依次下发应当取均值，同时下发应当求和）

此提案还可以解决当前：部分边缘节点由于被指派给了特别远的验证节点，导致网络连接不稳定，POA失败的情况。（只有在指定的3-5个验证节点都失败的情况下才算失败）

**Comment by MaryTitan** [comment]
Thank you for you advice. We will update this feature soon.
