### ISSUE TITLE
cant bind code

### ISSUE THREAD

**Issue by secretBabu** [Titannet-dao/titan-node#48]
could not get api info for edge: github.com/Filecoin-Titan/titan/cli/util.GetRawAPI

API not running (no endpoint)

**Comment by MaryTitan** [comment]
I need details to save your problem. Can you do screenshoots of your log, both edge log and today's log.

**Comment by secretBabu** [comment]
sorry  i cant find the log

**Comment by secretBabu** [comment]
and i start the program as administrator ， then  ok
