### ISSUE TITLE
winserver networkerror

### ISSUE THREAD

**Issue by zjg-scott** [Titannet-dao/titan-node#51]
winserver bind ID network error,how to handle it

**Comment by MaryTitan** [comment]
I need details to save your problem. Can you do screenshoots of your log, both edge log and today's log.

**Comment by MaryTitan** [comment]
Or you can try to restart the node, run it for a while until there are rewards, then bind the code and the last digit of the code needs to be entered manually.

**Comment by zjg-scott** [comment]
ok,i will try again after accumulating a certain amount of rewards
